GET#show:
  desc: Show password
  path: /password/reset
  requires:
    - dialog

POST#create:
  desc: Create password
  path: /passwords
  requires: []

GET#reset:
  desc: Reset password
  path: /passwords/:reset_token/reset
  requires:
    - no_user

GET#edit:
  desc: Edit password
  path: /passwords/:reset_token/edit
  requires:
    - user

PUT#update:
  desc: Update password
  path: /passwords
  requires:
    - user

